SLEEP_STATUS = {
    "om": "s",
    "pwr": "1",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "M",
    "pm25": 2,
    "iaql": 1,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}

SPEED_1_STATUS = {
    "om": "1",
    "pwr": "1",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "M",
    "pm25": 12,
    "iaql": 3,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}

SPEED_2_STATUS = {
    "om": "2",
    "pwr": "1",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "M",
    "pm25": 20,
    "iaql": 4,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}

SPEED_3_STATUS = {
    "om": "3",
    "pwr": "1",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "M",
    "pm25": 23,
    "iaql": 5,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}

TURBO_STATUS = {
    "om": "t",
    "pwr": "1",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "M",
    "pm25": 20,
    "iaql": 4,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}

OFF_STATUS = {
    "om": "t",
    "pwr": "0",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "M",
    "pm25": 20,
    "iaql": 4,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}

# TODO: Get an actual alergen mode response!
ALERGEN_MODE = {
    "om": "s",
    "pwr": "1",
    "cl": False,
    "aqil": 0,
    "uil": "0",
    "dt": 0,
    "dtrs": 0,
    "mode": "A",
    "pm25": 2,
    "iaql": 1,
    "aqit": 4,
    "ddp": "0",
    "err": 0,
}
