language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -e .
  - pip install -r requirements_dev.txt
script:
  - black --check setup.py test philips_air_purifier
  - flake8 setup.py test philips_air_purifier
  - pytest