language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
- pip install -r requirements_dev.txt
script:
- black --check setup.py tests philips_air_purifier
- flake8 setup.py tests philips_air_purifier
- pytest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: urbas
  password:
    secure: Hn1aLVYBxv/6L+XiYr/mrBrsWABkeGV4JxejFHi/HMT4kdrfizLXnFcyoI/WVSx/EYttED1XIQB1OMN/xfPJVyF45nfx5Qp/D0qoJLwONbJYlWiCfrLEIz/9LviyayrdtO2z59ttOJuCNd91o1WACk7T4cutVP9H1CV41M+FVxZlTaZaLI/pCbjlnPAQN+d6Lh2/jaSUaShB6ZfJ7p7yqgoRZPF/x0CnV73Qchhzv8BtjRWDwNiV2aSfT35mp0t+LaAu4AbEm5s4MxoeHdrkchB8wKnq9/UyYh2kVMTKMWkhhxccEfAzGmw50D4hCEEG4bHw0yUTrwn4vEnTwMaxoUBjb4C9YbuSFbd9igNfbBUeZzjPpglUxUdkrrlWjxvi1n9x6aMZQvmsgVwT17iagAnYaXn/e6Q+f2bjoyDuBblhP/t9agkotUrFhR4IATMSR2Ye1Bd0Of6IvQtiNcUAd+mbiPu7muCG+PdNxqS6LD5a7IunFlFMFsJQ0vDM9V9yFvD9GdNt+ulUq0e9P9QDjdJfWBUuFZMdA8DTAcxCcILUS8pdLyMKw2AuIeajycKr6zSOJ6a+riBqsYZ2JgZikslNHWH7jC9H/NwKqGZspd8uan7R3AKAaIaSZlsWPCPNbI19Fp6CkH2EyoJtaHPpuWCtuiT07qJtGOoTfaFq8z4=
  on:
    tags: true
    repo: urbas/philips-air-purifier
    python: '3.7'
