language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install -e .
- pip install -r requirements_dev.txt
script:
- black --check setup.py tests philips_air_purifier
- flake8 setup.py tests philips_air_purifier
- pytest tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: cwQC46QrvMEXf70QbcCP5tRW1lw/Qn/W/HymDUWvU1bTDa7ew+qXKEmSTcvkYu2erbbHMAcE/NcgxZt7TBfHp0Qdb9C0OJgCi9XAXVLBwpgk1JjAU7iOgjByzsdvTaoLU90d0jgPKnlgL5cQ3HK/HUSvP+LZUVyTx6+HvMgzik4aCgl43uLgZgnsDtvyffKM3ipOnIRD0OIZz8Tlol61lNihlR1cfp38W/P+DRDGkY7TKIVssf7k24GzfL1Jwisza2vEhhI4UFh/bH7YB/ICDon+2pQq9DxPNF5laOV0IUY/vvt16q9QjX/Ek3r81yIxEdvd574auWROepIuo9A/7XghQ/gbZHVOBzTEHpk9KYFItBWlz4MznXyaNNQLP5nm2na67HrtgQ2ChVolynoqhh3vofr/SUAPhPwgzwW6gXs0hetZayqCYNLt/MFeSo/L0/1s7/lYCnGe6t2sWoyr+ieVVJT79wtzP05tV1pkE5jzPn3H/WCpyH0QyA5cCPFiUlYEm5R/bvYuvvA6RIqXPFkcad+8sav7aG3aGt19Alp6FA3TKsJ5is9eDX4zeYZXphVaVvfSf6P1cnDEdkB9w2WPE5DhgAbaFpOQKr1vlzh9ctND6bK8gK2Iw6I1qJdhJt8Mzfie28v3lS+IeD0loCa1LSQJ5S9J3+0CNqhpJWs=
  on:
    tags: true
    repo: urbas/philips-air-purifier
    python: '3.7'
